---
- name: Set apache restart handler variables
  set_fact:
    apache_service: "{{ apache2_name }}"
    apache_restart_state: reloaded

- name: Enable SSL on default site
  template:
    src: etc/{{ apache2_name }}/{{ apache2_vhosts_conf_dir }}/{{ default_vhost_filename }}.LE.j2
    dest: /etc/{{ apache2_name }}/{{ apache2_vhosts_conf_dir }}/{{ default_vhost_filename }}
    backup: true
  notify: restart apache
  when: default_cert_retest is defined
    and default_cert_retest.stat is defined
    and default_cert_retest.stat.exists

- name: Disable the factory default site on EL Apache 2.2 (we already set up in the welcome file)
  template:
    src: etc/{{ apache2_name }}/{{ apache2_vhosts_conf_dir }}/ssl.conf.LE.apache-22.j2
    dest: /etc/{{ apache2_name }}/{{ apache2_vhosts_conf_dir }}/ssl.conf
    backup: true
  notify: restart apache
  when: default_cert_retest is defined
    and default_cert_retest.stat is defined
    and default_cert_retest.stat.exists
    and ansible_os_family == 'RedHat'
    and apache_version is version('2.4.0', '<' )
