---
- name: Fail when apache doesn't exist
  shell: test -x /usr/sbin/apache2
  changed_when: false
  
- name: Fail when apache isn't 2.4
  shell: /usr/sbin/apache2 -v | grep -q 'Apache/2.4'
  changed_when: false
  
- name: Set apache restart handler variables
  set_fact:
    apache_service: apache2
    apache_restart_state: reloaded

- name: Create apache includes dir
  file: 
    path: "/etc/apache2/includes"
    state: directory
  notify: restart apache

- name: Create apache acme-challenge conf
  template:
    src: "etc/apache2/includes/letsencrypt-acme-challenge.conf.j2"
    dest: "/etc/apache2/includes/letsencrypt-acme-challenge.conf"
    force: yes
  notify: restart apache
  
- name: Grep for the acme include in default Apache site
  shell: grep -q 'Include /etc/apache2/includes/letsencrypt-acme-challenge.conf' /etc/apache2/sites-available/000-default.conf
  register: acme_grep_result
  ignore_errors: true
  changed_when: false

- name: Reset default site to non-ssl version
  template:
    src: "etc/apache2/sites-available/000-default.conf.pre-ssl.j2"
    dest: "/etc/apache2/sites-available/000-default.conf"
    backup: yes
  when: acme_grep_result.rc != 0
  notify: restart apache

- name: Enable the default site
  file: 
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: "link"
    src: "/etc/apache2/sites-available/000-default.conf"
  notify: restart apache

- name: Reload apache if necessary
  meta: flush_handlers

- name: Automatically renew LE certs with cron
  cron: 
    name: "Renew letsencrypt SSL certificates"
    minute: "5"
    hour: "7"
    job: "/usr/local/bin/certbot-auto renew --quiet --no-self-upgrade && /usr/sbin/apachectl configtest 2>&1 | /bin/grep -v 'Syntax OK' || /usr/sbin/service apache2 reload"
  tags:
    - cron
