---
- name: restart apache
  service:
    name: "{{ apache2_name }}"
    state: restarted
- name: reload nginx
  service:
    name: nginx
    state: reloaded
- name: restart nginx
  service:
    name: nginx
    state: restarted
