---
- name: Converge
  hosts: all
  become: true

  vars:
    - default_mail_recipient: webmaster@acromedia.com
  pre_tasks:

    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes
        state: present

  roles:
    - role: ansible-role-letsencrypt
