---
- name: Converge
  hosts: all
  become: true

  vars:
    - default_mail_recipient: webmaster@xyz.com
    - letsencrypt_install_certbot_from_ppa: true

  roles:
    - role: ansible-role-letsencrypt
