- name: Prepare
  hosts: all
  become: true
  gather_facts: yes
  tasks:

    - name: Update yum
      yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'


    - name: Ensure python is installed
      package:
        name:
          - python3
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Update cache
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'


    - name: Ensure python is installed for Debian
      apt: pkg=python3 state=present update_cache=true
      when: ansible_os_family == 'Debian'

- name:  Install role dependencies that acromedia.letsencrypt will need
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Ensure dirmngr is installed
      apt:
        name: dirmngr
        state: present
      when: ansible_os_family == 'Debian'
  roles:
    - contrib/acromedia.nginx
