- name: Prepare
  hosts: all
  become: true
  gather_facts: yes
  tasks:

    - name: Update yum cache
      yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Update cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Ensure python3 is installed
      package:
        name:
          - python3
        state: present

    - name: Ensure dirmngr is installed (required to install software from PPAs)
      apt:
        name: dirmngr
        state: present
      when: ansible_os_family == 'Debian'

- name:  Install role dependencies that acromedia.letsencrypt will need
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - contrib/acromedia.nginx
