- name: Install nginx
  hosts: localhost
  connection: local
  become: no
  gather_facts: yes
  tasks:

    - name: Update yum
      yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Ensure nginx is isntalled
      package:
        name:
          - nginx
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure nginx is isntalled
      apt:
        name:
          - nginx
        state: present
      when: ansible_os_family == 'Ubuntu'
